package com.classproject.teacherapp.entity;

import lombok.Data;

@Data
public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_class.uuid
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_class.classname
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    private String classname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_class.teacher
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    private String teacher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_class.room
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    private String room;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_class.week
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    private String week;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_class.time
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_class.uuid
     *
     * @return the value of app_class.uuid
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_class.uuid
     *
     * @param uuid the value for app_class.uuid
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_class.classname
     *
     * @return the value of app_class.classname
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_class.classname
     *
     * @param classname the value for app_class.classname
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_class.teacher
     *
     * @return the value of app_class.teacher
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public String getTeacher() {
        return teacher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_class.teacher
     *
     * @param teacher the value for app_class.teacher
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public void setTeacher(String teacher) {
        this.teacher = teacher == null ? null : teacher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_class.room
     *
     * @return the value of app_class.room
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public String getRoom() {
        return room;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_class.room
     *
     * @param room the value for app_class.room
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public void setRoom(String room) {
        this.room = room == null ? null : room.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_class.week
     *
     * @return the value of app_class.week
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public String getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_class.week
     *
     * @param week the value for app_class.week
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public void setWeek(String week) {
        this.week = week == null ? null : week.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_class.time
     *
     * @return the value of app_class.time
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_class.time
     *
     * @param time the value for app_class.time
     *
     * @mbg.generated Mon Mar 02 13:28:48 CST 2020
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}