package com.classproject.teacherapp.entity;

import lombok.Data;

@Data
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.id
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.username
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_user.password
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.id
     *
     * @return the value of app_user.id
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.id
     *
     * @param id the value for app_user.id
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.username
     *
     * @return the value of app_user.username
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.username
     *
     * @param username the value for app_user.username
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_user.password
     *
     * @return the value of app_user.password
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_user.password
     *
     * @param password the value for app_user.password
     *
     * @mbg.generated Mon Mar 02 13:29:18 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}